export let images =
	['zhu_photo', 'park_photo', 'liang_photo', 'zhu_major', 'park_major', 'liang_major', 'zhang_photo', 'computer']
	.map(e => ({name: e, src: "./images/" + e + '.jpg', image:undefined}))
export let interview_liang = {
	name: `LIANG`,
	inter1: `Jinhao Liang / Grace Park`,
	"1": `+:name [JL] +:text I see your information, and you said you were brought up in Vancouver, but you want to move to Korea. So, which culture do you prefer? +:name [GP] +:text Sorry? +:name [JL] +:text Which culture do you like? +:name [GP] +:text What do I like? I think I like living in Vancouver more than Korea. Because I felt more free living in Vancouver. +:name [JL] +:text Why do you decide to move back to Toronto? +:name [GP] +:text I wanted to study in Toronto because I want to study somewhere that has diversity. Because in Korea, there is no diversity, and everything is so intense and strict. I think so. So, yeah. +:name [JL] +:text When are you coming to OCAD? +:name [GP] +:text When did I come to OCAD? This summer. +:name [JL] +:text I see you like to listen to all kinds of music. What music do you favour? +:name [GP] +:text I like R&B, or hip-hop, or sometimes country, or jazz, like everything. +:name [JL] +:text I see your degree is Drawing and Painting. What are you usually doing in the class? +:name [GP] +:text In class? Well, I have a painting class and a drawing class in the studio, so I usually just paint or draw. And I also did a collage yesterday in the drawing class. +:name [JL] +:text How long is the class? +:name [GP] +:text How long? Three hours. +:name [JL] +:text That’s good. Okay, another question, you like doing yoga? +:name [GP] +:text ​Yeah. +:name [JL] +:text ​Do you usually do yoga a week? +:name [GP] +:text ​How often? Twice a week, or once a week. +:name [JL] +:text ​Okay. Bye.`,

	inter2: "Jinhao Liang / Yi Zhang",
	"2": `+:name [YZ] +:text I want to be a designer in the future, so I chose this program. +:name [JL] +:text What kind of design do you like? +:name [YZ] +:text Pardon? +:name [JL] +:text What kind of design do like, do you favour? +:name [YZ] +:text I think it is the graphic design because I think it is easier than another design like the environment or the game design. So I chose the graphic design. +:name [JL] +:text What is the big challenge for you? +:name [YZ] +:text In the OCAD? My big trouble is the language. My English is not really good, and actually I can’t understand a lot of the professors, what did they say in the class, so it is hard to understand and to do some assessment. +:name [JL] +:text Do you think your English is improving? +:name [YZ] +:text I don’t think so, because I don’t like to talk with other people, so I can’t improve my communication. But I try to improve my English in OCAD. +:name [JL] +:text What time do you start playing the CS2? +:name [YZ] +:text What time? +:name [JL] +:text Yes, when do you start? +:name [YZ] +:text Actually, if I don’t have class, I always play CS2 in my free time. I think it is a good way to spend time and I love this game. +:name [JL] +:text Okay. Which class is your favourite class in OCAD? +:name [YZ] +:text My favourite class is the Design Process 1 because that professor is very kind to me. Her class is very interesting and even though I can’t understand all of what she said, I try my best to learn that. +:name [JL] +:text Do you like living in Toronto? +:name [YZ] +:text Pardon? Sorry. +:name [JL] +:text Do you like living in Toronto? +:name [YZ] +:text I think I love Toronto’s weather. I think this area is very fresh and the weather is very cold, so it is my favourite thing in Toronto.`,

	inter3: "Jinhao Liang / Chenen Joan Zhu",
	"3.1": `+:name [JL] +:text Why did you choose this degree? +:name [CZ] +:text I chose this major because I studied jewellery design in my high school, but OCAD didn’t have jewellery design in the first year, so I studied material art and design. And why I choose to study jewellery design? Because I’m not interested in painting something, and I’m terrible at painting a sketch, so I chose to do some artwork by my hand, just like some crafts. +:name [JL] +:text Do you make any projects? +:name [CZ] +:text Yes, and I study a course about sculpture. Yes, I studied this program. It is a little bit difficult for me because this program needs to talk to others, and also I’m a little bit afraid to talk to my professors, and I never tried to do some sculpture before. So, it’s difficult for me, yes. +:name [JL] +:text Do you usually make things for yourself or for others? +:name [CZ] +:text I always make things—actually, I like to make things for others, because I think I always want to just give some things for my friends, because when they are happy, I’m also happy. +:name [JL] +:text What computer games do you usually play? +:name [CZ] +:text Computer games, I like to play the Strawberry Valley and Minecraft, just these games, and others I don’t try. Maybe I will try in the future, other kinds of games. +:name [JL] +:text Do you prefer making small things or big things? +:name [CZ] +:text Actually, I like to make some small things. You know, I’m the jewellery designer, so making the small things is easier for me, just like the rings and others, yes. The big things are so big and it’s more difficult to do, and also I never tried to do the big things before, so the small things are better for me, yes. +:name [JL] +:text Do you get inspiration from nature or people? +:name [CZ] +:text What? +:name [JL] +:text Inspiring. From nature or people? +:name [CZ] +:text Nature. Of course, it’s from nature. I don’t like to communicate with people face to face right now, so maybe I will just go to the park when I have time, and I will just sit in the swings and play with the leaves, yes. I like the nature better than people. +:name [JL] +:text Do you like working alone or working with my friends or with other people? `,

	"3.2": `+:name [CZ] +:text I think both. Most of the time I like doing things by myself, but if there are other people doing the same things together with me, I will have the stress and I will think I can do this project faster—when I was alone, I would finish this become the deadline, yes. +:name [JL] +:text Do your family support your art? +:name [CZ] +:text Support my art, I think it’s yes. They support me to come here and support me for my study, for my art, yes.`

}
export let interview_zhang = {
	name: 'Yi Zhang',
	inter1: 'Yi Zhang / Grace Park',
	
	"1.1": `+:name [YZ] +:text Hi. +:name [GP] +:text Hi. +:name [YZ] +:text And what program are you studying at OCAD? +:name [GP] +:text I’m studying Drawing and Painting. +:name [YZ] +:text Oh, that’s cool. And why did you choose that major? +:name [GP] +:text Well, since I was young, I just like to draw and paint. And I just love— +:name [YZ] +:text Love painting? +:name [GP] +:text love anything visual, anything like visual things, like visual culture, anything visual. +:name [YZ] +:text Oh, okay. And what kind of project have you enjoyed the most so far? +:name [GP] +:text I’m having a painting class, and right now I’m doing an abstract still life painting. And it’s actually my first time doing an abstract painting, and I’m really enjoying it. It’s really interesting. +:name [YZ] +:text And I know you love to listening the music, so what kind of music do you like the most? +:name [GP] +:text The most? +:name [YZ] +:text Yeah, the most. +:name [GP] +:text Recently, I like R&B. +:name [YZ] +:text Oh, me too. +:name [GP] +:text And a little bit of hip-hop. Do you like it? +:name [YZ] +:text Yeah, K-pop. +:name [GP] +:text No, hip-hop—oh K-pop. +:name [YZ] +:text K-pop? Hip-hop. Okay. And who is your favourite singer? +:name [GP] +:text Singer? +:name [YZ] +:text Yeah. +:name [GP] +:text Only one? +:name [YZ] +:text Yeah, only one. The favourite. +:name [GP] +:text Favourite. +:name [YZ] +:text Yes. +:name [GP] +:text You know Daniel Caesar? +:name [YZ] +:text Daniel Caesar? No. +:name [GP] +:text Yeah, he’s a Canadian singer, I like him. +:name [YZ] +:text Oh, okay. And which hobby would spend you the most time to do it? Like the painting? +:name [GP] +:text I think it’s drawing and reading. +:name [YZ] +:text Oh, reading. Yeah, and how long you keep to do it, the reading? +:name [GP] +:text Reading? Like, how long? +:name [YZ] +:text How long, and how often you have to do it? +:name [GP] +:text How often? Almost . . . I try to read like almost every day, but it’s kind of impossible. But I try to. +:name [YZ] +:text Oh, okay. I love to read, too. And sorry, where are you from? +:name [GP] +:text From Korea. +:name [YZ] +:text Can you introduce your city in Korea? +:name [GP] +:text Sorry? +:name [YZ] +:text Can you introduce your city? +:name [GP] +:text Oh, city. +:name [YZ] +:text Yeah. What’s the name? +:name [GP] +:text In Korea? +:name [YZ] +:text Yeah. +:name [GP] +:text It’s called Daejeon. +:name [YZ] +:text Daejeon? +:name [GP] +:text Daejeon, yeah. It’s not like the biggest city as like, you know, Seoul? +:name [YZ] +:text Yeah, I know that.`,

	"1.2":  `+:name [GP] +:text It’s not that big, but we have like nature and some city things. +:name [YZ] +:text It’s near for the . . . +:name [GP] +:text Yeah, it’s pretty close, like two hours. +:name [YZ] +:text Okay. And are there any famous buildings in your city? +:name [GP] +:text Famous buildings? I don’t think so. +:name [YZ] +:text Oh, that’s okay. And what is your favourite things in your city that you do the most? +:name [GP] +:text Favourite? +:name [YZ] +:text Yeah, favourite. +:name [GP] +:text Favourite things. Um, there was like a really, really good bakery. +:name [YZ] +:text Oh? +:name [GP] +:text It was like really delicious, and I love that. +:name [YZ] +:text I love to eat delicious food, too. And do you play the game? +:name [GP] +:text Um, no. +:name [YZ] +:text Oh, Okay. Why don’t you play the game? +:name [GP] +:text Well, I did like a few years ago. +:name [YZ] +:text You tried to play? +:name [GP] +:text Yeah, but I’m not good at it. +:name [YZ] +:text Oh, I’m sorry to hear that. +:name [GP] +:text That’s okay. +:name [YZ] +:text And your hobby is reading. Can you tell me the book’s name when you read now? +:name [GP] +:text Like reading now? Um, I’m reading . . . it’s called +:italic The Art of Thinking Clearly. +:/reset It’s about thinking clearly. +:name [YZ] +:text Oh, okay. That’s interesting. So, that’s all. Thank you. +:name [GP] +:text Thank you. +:name [YZ] +:text Okay.`,

	inter2: 'Yi Zhang / Chenen Joan Zhu',

	"2.1":  `+:name [YZ] +:text Hi. +:name [CZ] +:text Hi. +:name [YZ] +:text What is your program will you study at OCAD? +:name [CZ] +:text My program is Material Art and Design, and I studied jewellery design in my high school, and, well, in the first year we don’t have the jewellery design, so I studied the Material Art and Design. +:name [YZ] +:text That’s interesting. And why did you choose that major? +:name [CZ] +:text Actually, I think I chose this major because . . . At first I wanted to choose another major, but— +:name [YZ] +:text Woah. +:name [CZ] +:text Yes, because my painting is very terrible, so I put my attention on the— +:name [YZ] +:text Design. +:name [CZ] +:text Yes, design, and just make some other artwork. +:name [YZ] +:text Oh, okay. +:name [CZ] +:text So I chose this major. +:name [YZ] +:text And what kind of project have you enjoyed the most so far? The project or the object? +:name [CZ] +:text I think it’s the sculpture courses, because these courses are a little bit difficult for me, so I try to follow the . . . +:name [YZ] +:text The professor. +:name [CZ] +:text Yes, the professor. +:name [YZ] +:text Okay. And I know you love to play the game, and I want to know what kind of games do you love to play? +:name [CZ] +:text Okay. Two kinds of games I play is, sometimes it’s on my phone, and sometimes it’s on my computer, and on my computer I like to play the games like Stardew Valley and Minecraft. This kind of game. +:name [YZ] +:text Oh, I play it too. +:name [CZ] +:text Yeah. I always play the . . . I usually spend many time to play on this game. And sometimes I will play it on my iPad, play the games like Identity V or Arknights. +:name [YZ] +:text Oh, okay. And . . . which hobby would spend you the most time to do it? +:name [CZ] +:text I think the hobby I spend most time is do some . . . +:name [YZ] +:text Do some . . . +:name [CZ] +:text Just sometimes I will . . . just watching the anime. It’s my favourite thing that I like to do in the weekend. I usually spend a lot of time to watch the anime. +:name [YZ] +:text Oh, which kind of anime you watch the most? +:name [CZ] +:text Sometimes it’s the sports anime. Yes. +:name [YZ] +:text Ooh. And can you tell me the name? Maybe Chinese name is okay. +:name [CZ] +:text I know the Japanese— +:name [YZ] +:text Oh. +:name [CZ] +:text It’s Daiya no Ēsu. +:name [YZ] +:text Oh. Okay.`,
	"2.2": `+:name [CZ] +:text The baseball anime. Yeah. +:name [YZ] +:text And how long you keep to do it, like to watch cartoons? +:name [CZ] +:text ​How long? Every time when I was . . . Not every time, but when I have time, I will watch them. Or sometimes when I eating something, like in my lunch or my dinner, I will find something to watch. It’s a great way to spend my time. Yes. +:name [YZ] +:text Yeah. Okay, and where are you from? +:name [CZ] +:text I’m from China, Guangdong, China. This is a city near the sea. It’s a coastal city. I live in Zhuhai, Guangdong, it’s a coastal city. Actually, this city have the typhoon every year. Oh. So— +:name [YZ] +:text So dangerous. +:name [CZ] +:text Sometimes it’s dangerous, yes. And I usually go to the beach when I was young and I have fun with my friends, with my family, near the beach, yes. +:name [YZ] +:text Okay, thank you. +:name [CZ] +:text Thank you very much.`
}
export let interview_park = {
	name: "Grace Park",
	inter1: "Grace Park / Jinhao Liang",
	'1.1': `+:name [GP] +:text I heard that you lived in China, right? So what was your favourite thing about living there in China? +:name [JL] +:text I think . . . Can you ask me again? +:name [GP] +:text Like, what was your favourite thing about living in China? +:name [JL] +:text I think maybe playing badminton with my friends. +:name [GP] +:text Oh yeah. Then how do you find living here in Toronto, compared to China? How’s it different? +:name [JL] +:text I think the traffic convenient. Because living in Toronto, it’s a big city— +:name [GP] +:text Yeah, it is. +:name [JL] +:text And I don’t have a car— +:name [GP] +:text Yeah, I don’t have it either. +:name [JL] +:text I need to go outside and wait to take the bus. I need to wait a long time. But in China, I have a car, so I don’t need to wait. +:name [GP] +:text Do you live in an apartment or a student residence here, or . . . ? +:name [JL] +:text I might have an apartment. No reason. +:name [GP] +:text Okay. Is there any places you want to recommend here around OCAD, like our school? Like, any food places or . . . places like anywhere you like to go? +:name [JL] +:text I usually stay at home, so I— +:name [GP] +:text Oh yeah, me too. Okay, then . . . Are you in any clubs? I heard that there’s a lot of clubs here in OCAD, so . . . +:name [JL] +:text I don’t join any clubs. Because I’m an introvert person, so I don’t have any activity. +:name [GP] +:text Me neither. Okay, then, what kind of hobbies do you have? +:name [JL] +:text Badminton. +:name [GP] +:text Badminton. I heard that you like to draw, right? What kind of drawings do you like to do? +:name [JL] +:text Sketches. +:name [GP] +:text Sketches? Like figures or abstracts or.. +:name [JL] +:text I don’t know. I just like the sketches, like the white and black kind. +:name [GP] +:text Are you in the Drawing and Painting program? +:name [JL] +:text Yes. +:name [GP] +:text Oh, me too. That’s great. What do you think about the Drawing and Painting program so far? Are you enjoying it? Is it challenging? +:name [JL] +:text I think . . . it’s the language. I can’t understand the professors. +:name [GP] +:text Oh yeah, that’s hard. What’s your favourite class in our program? +:name [JL] +:text Maybe . . . maybe it’s my Environmental Design class. +:name [GP] +:text Oh, Environmental Design class, that’s so cool. What kind of projects do you do in that class? Like assignments.`,
	'1.2': `+:name [JL] +:text In class, I usually to do some modelling and some drawing. +:name [GP] +:text Drawings? +:name [JL] +:text Yes. And the teacher teach me to draw the floor plan. +:name [GP] +:text Oh, I see. I think that’s pretty much it. Um okay, lastly, could you recommend anything here in OCAD? Just one thing, for the future students. +:name [JL] +:text It’s difficult for me to recommend. I don’t have anything. +:name [GP] +:text Like anything—anything you like the most in this school. +:name [JL] +:text Hmm . . . +:name [GP] +:text Okay, you’re still finding. Yeah, it’s been only two months, I understand. Okay, thank you.`,

	inter2: 'Grace Park / Yi Zhang',
	'2.1': `+:name [GP] +:text Hi, Yi. You’re from China, right? +:name [YZ] +:text Yup. +:name [GP] +:text What’s your favourite thing about living in China? +:name [YZ] +:text My favourite thing in China is to eating some delicious food, like the dumplings or the noodles, hotpot. +:name [GP] +:text I love hotpot a lot. I love them. +:name [YZ] +:text I love it too. +:name [GP] +:text Yeah. So, how do you find living here in Toronto compared to China? Is it better, or . . . ? +:name [YZ] +:text I think definitely the weather. +:name [GP] +:text The weather? +:name [YZ] +:text Yeah. I think Toronto’s weather is very cold than the area which I lived in China. So I think, very cold for me. +:name [GP] +:text Oh yeah. And what places would you like to recommend here around OCAD, or just in Toronto? +:name [YZ] +:text Sorry, pardon? +:name [GP] +:text Oh—like what places would you like to recommend, like places you like to go around here? +:name [YZ] +:text Around here? Yeah, I think . . . I’m sorry, I’m not the kind of person who likes to hang out in the outside, so . . . +:name [GP] +:text That’s okay. So, then where’s your—do you have any, like, favourite place in our school? Any food places or cafés, or the library, or the park? +:name [YZ] +:text Yeah, I think it’s the park. The park is very beautiful. +:name [GP] +:text Yeah, it is. +:name [YZ] +:text Yeah. Especially when I—after the class to hang out with my friends in that park, I think it’s very comfortable and it can let my hair down, so I love the park. +:name [GP] +:text Great. And you’re studying graphic design, right? +:name [YZ] +:text Yup. +:name [GP] +:text Why did you choose that specific major? +:name [YZ] +:text Yeah, because I love the design very much. When I was a little child, I loved design. Design anything—about the animals, design the drawings, design the cards, so . . . When I was a little kid, I wanted to be a—my dream is to be a graphic designer. +:name [GP] +:text That’s so cool. +:name [YZ] +:text So I chose that. +:name [GP] +:text Perfect. Are you enjoying it? Like, how’s the program so far?`,

	'2.2': `+:name [YZ] +:text Yeah, of course. Yeah, graphic design—I think Design Process is very interesting. You can—yeah, I very enjoy to do that, about finding something and check the photo to make sure they are pretty and . . . yeah. +:name [GP] +:text Okay. Then, do you have any hobbies? +:name [YZ] +:text Yeah, my hobby is stay at home and play the game. +:name [GP] +:text Oh, yeah. Is there any other things? +:name [YZ] +:text Actually, except play the game, my hobby is the painting. +:name [GP] +:text Painting. What kind of mediums do you use usually? +:name [YZ] +:text I use the iPad. +:name [GP] +:text Oh, like digital drawing? +:name [YZ] +:text Yeah, the most. +:name [GP] +:text Procreate? +:name [YZ] +:text Yeah, yeah. +:name [GP] +:text Yeah, that’s great. Okay. Are you in a club or something? +:name [YZ] +:text No, I’m not. I don’t like have— +:name [GP] +:text Like social activities? +:name [YZ] +:text Yeah, yeah. I’m very afraid that. +:name [GP] +:text Okay, that’s okay. Okay, lastly, what would you like to recommend—like one thing, if you can recommend one thing in this school, like anything, what would you like to recommend to the future students? +:name [YZ] +:text I think it’s only one thing I want to tell them is that you don’t need to buy any design app in your PC. +:name [GP] +:text Oh, yeah. +:name [YZ] +:text You don’t need to buy it. +:name [GP] +:text Yeah, true. Okay. +:name [YZ] +:text You don’t need have to spend money. +:name [GP] +:text Yeah. Did you? Did you spend money? +:name [YZ] +:text Yeah. +:name [GP] +:text Oh! +:name [YZ] +:text Yeah, so I want to tell them! +:name [GP] +:text Okay, okay. +:name [YZ] +:text Yeah, that’s all? +:name [GP] +:text Yeah, thank you. +:name [YZ] +:text Thank you.`,

	inter3: "Grace Park / Chenen Joan Zhu",
	'3.1': `+:name [GP] +:text Hi Joan. +:name [CZ] +:text Hi. +:name [GP] +:text You were born and raised in China, right? +:name [CZ] +:text Yes, in China. +:name [GP] +:text So, what was your favourite thing about living there? +:name [CZ] +:text Um, what? +:name [GP] +:text Favourite thing about living there in China. +:name [CZ] +:text Favourite thing? Many things. The activity or the—eating something or just something. +:name [GP] +:text I like Chinese food. +:name [CZ] +:text Chinese food is very good. And I’m from Guangdong. So, I think, how to . . . We also always eat in the morning—I forgot the word, but I like the changfen here, it’s made by the eggs and the vegetables— +:name [GP] +:text Oh, I think I know that. +:name [CZ] +:text Oh, yeah. It’s very delicious and I miss it. +:name [GP] +:text That’s so cool. Okay. Then, do you live in an apartment or a student residence here? +:name [CZ] +:text Here, I live in an apartment, but the apartment is a studio. It’s a very small studio. +:name [GP] +:text Oh, Okay. Then, how do you find living here in Toronto compared to China? +:name [CZ] +:text Compare with living here and China? Definitely living in China is better, because living here, I just live with myself, and sometimes, I will feel alone, and in China, there’s my friendsm and also, I live with my parents, my sister, my brother, family, eveything, community together. +:name [GP] +:text Yeah. Is there any places you would like to recommend here around OCAD or in Toronto? +:name [CZ] +:text I see just the park near the OCAD. +:name [GP] +:text Oh, yeah. The Butter . . . Butterfield, is it? Right? +:name [CZ] +:text I forgot the name. +:name [GP] +:text Yeah, but I like that park, too. +:name [CZ] +:text Yeah, I like the park. Yeah, the park is very fun. +:name [GP] +:text Yeah, it’s fun. +:name [CZ] +:text I like to play the swings in the park. +:name [GP] +:text Yeah, it’s really relaxed. +:name [CZ] +:text And the leaves, they’re beautiful. +:name [GP] +:text Mmhm, I love the nature there. So, you’re majoring in Material Art and Design? +:name [CZ] +:text Yes. +:name [GP] +:text Why did you choose that specific major? +:name [CZ] +:text Actually, I studied jewellery design in my high school. +:name [GP] +:text Oh, yeah?`,

	'3.2': `+:name [CZ] +:text I studied jewellery design and OCAD doesn’t have jewellery design in the first year, so I chose this major. So, why chose jewellery design? Because painting is difficult for me. Painting is always difficult for me. +:name [GP] +:text Oh. +:name [CZ] +:text Because I’m terrible at drawing the sketch. +:name [GP] +:text It’s okay. That’s okay. +:name [CZ] +:text I think it was my intention to do some crafts. Yeah, some crafts. +:name [GP] +:text Yeah. +:name [CZ] +:text So, I chose this. +:name [GP] +:text You also like to do handicrafts, right? +:name [CZ] +:text Yes, handicrafts. +:name [GP] +:text What kind of crafts do you do? +:name [CZ] +:text Metal work. But doing some mental work needs a very—I need a place, but a place I can’t easily to find. So, in my home, I will do some . . . I will do some little dolls by myself. +:name [GP] +:text Okay. What’s the most interesting part of your program? +:name [CZ] +:text My interesting part, I think, is doing handicrafts. +:name [GP] +:text Handicrafts. +:name [CZ] +:text Yes. Actually, I’m a little bit afraid to talk with others, so most of the time, I’m just doing my things by myself. +:name [GP] +:text That’s good. And what kind of projects, like assignments, did you do in your program? +:name [CZ] +:text I’m studying another program, it’s called Sculpture. +:name [GP] +:text Oh, wow. +:name [CZ] +:text I’m studying sculpture. So, this program is a little bit difficult for me. Because I’ve never done so much things. Actually, this course is most like fine arts, but a little bit difficult. +:name [GP] +:text Okay. So . . . Oh, are you in a club? +:name [CZ] +:text No. +:name [GP] +:text Okay, me neither. Me neither. +:name [CZ] +:text Maybe in the second year, I will try to join a club. +:name [GP] +:text Yeah, sure. We don’t have enough time now. +:name [CZ] +:text And . . . Is that okay? +:name [GP] +:text I guess that’s pretty much it. Okay, thank you. +:name [CZ] +:text Thank you so much.`

}
export let interview_zhu = {
	name: ``,
	inter1: `Chenen Joan Zhu / Jinhao Liang`,
	'1': `+:name [CZ] +:text Hello, and what’s your major and why did you choose your major? +:name [JL] +:text My major is Environmental Design because I like to design the space and create the buildings. +:name [CZ] +:text Okay, I saw that you play badminton. Have you tried any other exercise or just like playing badminton? +:name [JL] +:text I have to try, but my favourite one— +:name [CZ] +:text Like running or other sports? +:name [JL] +:text Swimming and volleyball. My favourite one is badminton. +:name [CZ] +:text Okay, how long did you play it before? I mean, when you grow up, you just play or you are starting to play it? +:name [JL] +:text I played badminton for a long time. +:name [CZ] +:text So, back to your major, back to your program. Do you want to use this major to earn some money in the future? +:name [JL] +:text I don’t know. I think it’s my interest, so I want to learn first. +:name [CZ] +:text ​Okay, so did you prefer reading or playing games? +:name [JL] +:text ​I don’t like playing games, I think playing games is so boring. But I usually watch movies or watch TV. +:name [CZ] +:text ​So, watch anime? Or just movies and some short movies like TikTok? Do you prefer to stay at home or go outside with your friends in the weekend? +:name [JL] +:text ​Um, because I’m an introvert person, so I prefer to stay at home to work. +:name [CZ] +:text ​So, when you stay at home, do you like cleaning your house or just do something you want to do? +:name [JL] +:text ​No. I just like to watch TV. +:name [CZ] +:text ​Yes, I’m also same. Just lying on my bed and sleeping and watching TV is better, yes. Another question, do you like Toronto? +:name [JL] +:text ​Um, I mostly like it. +:name [CZ] +:text ​Okay, I know. I know. So, I saw that you can speak Cantonese and Mandarin. So, you come from maybe Guangdong or Hong Kong— +:name [JL] +:text Yes— +:name [CZ] +:text Oh, I come from Guangdong too, but I don’t speak Cantonese. I can’t speak that. So, I want to ask you that you studied Cantonese when you grew up, or just your family taught you so you studied? +:name [JL] +:text ​Yes, my family taught me. +:name [CZ] +:text ​Okay, I think the time is enough. Thank you.`,

	inter2: `Chenen Joan Zhu / Grace Park`,
	'2.1': `+:name [CZ] +:text ​Okay, hello. +:name [GP] +:text Hi. +:name [CZ] +:text Why did you choose this major? +:name [GP] +:text This major? +:name [CZ] +:text Yes, and what is your major? +:name [GP] +:text I’m studying Drawing and Painting. +:name [CZ] +:text Okay. +:name [GP] +:text I guess I just like to draw and paint. I think there’s no special reason for that. +:name [CZ] +:text Okay. +:name [GP] +:text I just like it, really really like it. +:name [CZ] +:text Okay, so do you want to use this major to earn some money in the future? +:name [GP] +:text Oh, yeah, sure. If I can, I want to. +:name [CZ] +:text Become a designer? +:name [GP] +:text ​Yeah, or a painter, or maybe something else. +:name [CZ] +:text Okay, so great. And do you prefer reading or playing games? +:name [GP] +:text I don’t play games, but I like to read. +:name [CZ] +:text So, some people will listening to music when they read books. Do you prefer to listen to music or just reading in silence? +:name [GP] +:text Oh, I like to listen to music while reading. +:name [CZ] +:text Do you prefer to stay at home or go out with friends in the weekend? +:name [GP] +:text I like both, like sometimes I just stay at home and relax, but I like to go out. +:name [CZ] +:text So when you go out with your friends, do you like to go to the park or just have fun with friends? +:name [GP] +:text Just having fun. +:name [CZ] +:text And also when you stay at home, do you like to clean your house or just do something you want to do? +:name [GP] +:text I love to clean my house. +:name [CZ] +:text Oh—very, very cool. I just want to do something else, because I’m a very lazy person. +:name [GP] +:text It’s okay. +:name [CZ] +:text Yeah, so cool. And another question, do you like Toronto? +:name [GP] +:text Yeah, I do. Well, there are some crazy people, but I like it. There are some sweet people as well. +:name [CZ] +:text So cool. So what’s your favourite activity in Toronto? +:name [GP] +:text Activity in Toronto? +:name [CZ] +:text Yeah, taking photos or just . . . +:name [GP] +:text Oh, yeah, taking photos. There are so many cool places. +:name [CZ] +:text Can you tell me one of your favourite activities in the place you grew up? +:name [GP] +:text Oh, the favourite place. There was a beach in front of our house. So we like—I can’t remember the name, but it was my favourite place. `,

	'2.2': `+:name [CZ] +:text Oh, cool. I also live in the coastal city. Yeah, the beach is so great, but in the summer, it’s a little bit hot. And let me see, I saw that you come from Korea? +:name [GP] +:text Yeah. +:name [CZ] +:text And you also listen to music. Do you like K-pop? +:name [GP] +:text Okay, I do know K-pop, but I don’t really enjoy it. Do you like it? +:name [CZ] +:text Actually, no, but my little sister, she really likes K-pop. +:name [GP] +:text That’s great. +:name [CZ] +:text And she really admires the stars. Sorry, I don’t know— +:name [GP] +:text I don’t know. +:name [CZ] +:text Also, I want to know something—is there any delicious food in Korea? +:name [GP] +:text Food? +:name [CZ] +:text Yeah, food. +:name [GP] +:text You know the pancake? There’s a Korean pancake. Like potato pancake. +:name [CZ] +:text I like potatoes, so I think maybe it’s delicious. +:name [GP] +:text Yeah, it’s really good. +:name [CZ] +:text And, I don’t have any questions—maybe it’s enough. Finish right now, I think it’s okay. +:name [GP] +:text Okay.`,

	'inter3': 'Chenen Joan Zhu / Yi Zhang',
	'3.1': `+:name [CZ] +:text Hello. +:name [YZ] +:text Hi. +:name [CZ] +:text Why did you choose this major? +:name [YZ] +:text My major is Graphic Design, and I chose this major for only one reason, that I love design. When I was a little child, I loved designing the dress. When I go to the high school, I love to design the photos. +:name [CZ] +:text Do you want to use this major to earn more money in the future? +:name [YZ] +:text Yeah, of course, definitely, 100 percent. No because, actually, I want to be a graphic design worker in the future, so I think the answer is yes. +:name [CZ] +:text Okay, and next question, do you prefer reading or playing games? +:name [YZ] +:text Playing games, because reading books is a good way to improve myself. But playing games can make me more happy than reading books, so I choose that. +:name [CZ] +:text Okay, and do you like to talk to others when you’re playing games, or just playing by yourself? +:name [YZ] +:text I think it’s the first one, to have communication with others. Because I play the FPS game the most, so this game is the first-person shooting game, so I must speak with other people, so . . . yup. +:name [CZ] +:text Okay, and do you prefer to staying home or go out with your friends on the weekends? +:name [YZ] +:text Definitely stay at home and play with my friends on the weekends, but going out is good, too. +:name [CZ] +:text And when you go out, do you prefer to go to the park or just have fun with your friends? +:name [YZ] +:text I think it’s just have fun with my friends, because the time I stay with my friends, I feel more happy, and I think doing anything is interesting with them. +:name [CZ] +:text And when you stay at home, do you like to clean your house or just do something you want to do? +:name [YZ] +:text Cleaning house is maybe once a week, but I always choose the second one, because I love playing games, and I just want to do anything I want to do. +:name [CZ] +:text So, do you like Toronto? +:name [YZ] +:text Yeah, of course, I love Toronto, because Toronto has good views and good weather at this time, so even though I’m not usually to hang out, but I can stay at home and watch outside. +:name [CZ] +:text Okay, and what’s your favourite activity in Toronto?`, 

	'3.2': `+:name [YZ] +:text My favourite activity is play games. But in Toronto, my favourite activity is maybe hang out with my friends and stay at the park to breathe fresh air. +:name [CZ] +:text So, can you tell me one of your favourite activities in the country you grew up? +:name [YZ] +:text My favourite activity in my country? +:name [CZ] +:text Yeah. +:name [YZ] +:text Yeah I’m from China, so my favourite activity is eating— +:name [CZ] +:text Delicious food? +:name [YZ] +:text Delicious food, yes—I love it. Yummy, yummy. +:name [CZ] +:text Yes. +:name [YZ] +:text Okay, bye-bye.`
}

export let liang_major = `I took this photo of the CN Tower when I first came to Canada. It was one was one of the first places I visited because it is very close to my school. I went there with my friends and it was a bright sunny day. The tower look so tall and amazing. This moment was special for me because it made me feel nervous to start my new life and study in Toronto. Every time I see the CN Tower again I am reminded the feeling what I had.
—JL
`

export let park_major = `This is a picture of part of the Grange Park and OCAD. Since my first day of school here at OCAD, this park has been my favourite place among many other places. It always made me so comfortable and relaxed. Once, during my drawing class, we went to the park and drew the surroundings and people around there, and it was also a great experience.
—GP
`

export let zhang_major = `This photo shows the street outside my apartment near OCAD. I chose it because it represents my daily experience here and the small moments of calm I notice, even though I don’t go out much.
—YZ
`
 
export let zhu_major = `This photo I took in the Grange park near the OCAD. When I was there the weather was snowing. Because I come from the coastal city so this was the first time I saw snow in these years. I love the park when I come to the Toronto, I always play the swings when I have the spare time. And also yesterday I enjoyed the snow in there.
—CZ
`

export let zhu_amajor = `Here is a photo from my visit to our Material Art & Design department. I toured their ceramics studio and jewelry workshop, and discussed some metalworking related topics with the teacher in the jewelry classroom. I’m very eager to study in the studios, though that might not happen until winter or my second academic year.
—CZ
`

export let park_amajor = `This photo presents a part of the drawing class, doing observational drawings of some plants, a bicycle, and some other objects. In this class, we were practicing drawings that focus on the negative spaces. Although it was my first time doing this kind of drawing, I really enjoyed it and I was really happy to get to know the idea of negative spaces. So, that is why I chose this photo.
—GP
`

export let liang_amajor = `I took a photo of the Studio Room 240 because this room represents the learning space for Environmental Design students. We have the classes, work on projects, and learn design skills in this room. Even from the outside, the studio door shows the area where we study and create our work. I chose this photo because it shows the real space in which our discipline takes place.
—JL
`


// -----------------
// DISCIPLINE
// -----------------

export let grace = {
	major: "Drawing & Painting / Grace Park",
	name: "Grace Park",
	text: `My field of study is Drawing & Painting, and both of them are an essential part of visual art. Especially, I think drawing, which is a kind of art that you can visualize anything with any material on a paper or other surfaces, is the most important and fundamental skill in every field of art. The reason why I think like this is because it enables you to visualize your creative ideas, thoughts, and feelings through the creative process of expression.
Also, painting is very similar to drawing, since it is a way of visual expression. But I think painting goes a little bit further than drawing. It is a kind of art that applies wet medium such as paint, pigment, or colour to a solid surface using tools such as brushes and palettes, and eventually it helps us to engage in more dynamic expressions. Thus, I was curious about the beginning and the purpose of the painting, and I did a research about this topic. I learned that the history of painting starts back in the time to the artifacts and artwork created by prehistoric artists. And through this sentence, “Either way, a painted surface is an aggregation of time as much as it is an aggregation of marks upon a given surface,” +:marker [1] +:/reset I realized that painting engages with various aspects and events derived from the past.
Lastly, I’ve talked to my classmate Semi Heo, who is also in the Drawing & Painting program, and asked about her experience and ideas about this particular field of study. She told me that she feels like her range of expression has really expanded by keep getting lots of opportunities to work in different mediums and express them in different ways, and that was exactly why she chose this profession. I’ve also felt the same way as she said, and I think that is the best part of this area of study.
+:footnote [1] Craig Staff, “Painting, History and Meaning: Sites of Time,” in +:italic +:footnote Painting, +:italic +:footnote History +:italic +:footnote and Meaning +:notitalic +:footnote (United Kingdom: Intellect, 2022), 4.`
}

export let liang = {
	name: "Jinhao Liang",
	major: "Environmental Design / Jinhao Liang",
	text: `I study Environmental Design at OCAD University. For my research people start to care about how buildings and space affect our lives. Environmental Design is about planning and creating space. +:marker [1] +:/reset How the space is safe, comfortable, and good for the environment. In this program we will learn about the research, analysis, design and presentation and how to turn your ideas into real plans and environmental. +:marker [2] +:/reset This skill can connect ideas from architecture, interior design, and urban planning. +:marker [3] +:/reset People want to make places that help people live better.
I talked to my classmate Sam. He is also in this program. He told me he chose Environmental Design because he likes drawing and making with spaces. He said this program can be hard sometimes, especially when we need to make models or work with the classmates, because he can’t freely add some own ideas, but he said he enjoys learning new skills about this program. Sam hopes to work in interior design in the future. His thoughts helped me understand more about this major.
After my research and talk with a classmate, I know that Environmental Design is not only making things look nice. It is also about solving some problems in our life, like how people move in a space or how a building can save energy and protect the environment. This makes me feel more interesting in my program.
 
+:footnote [1] “Environmental Design,” OCADU, accessed 19 November 2025, https://admissions.ocadu.ca/program/environmental-design. 
+:footnote [2] “Environmental Design: Interior Design Specialization,” OCADU, accessed 19 November 2025, https://admissions.ocadu.ca/program/environmental- design-interior-design-specialization.
+:footnote [3] OCADU, “Environmental Design.”`
}

export let zhu = {
	name: "Chenen Joan Zhu",
	major: "Material Art & Design / Chenen Joan Zhu",
	text: `My major is Material Art & Design. This major includes three parts: Textiles, Jewellery, and Ceramics. They both have a long history in the art world, for example the history of ceramics can be traced back to the Neolithic Age approximately twenty thousand years ago, and the history of jewellery can be traced back to the Paleolithic Age approximately seventy thousand years ago, when early humans began using shells, bones, and stones to create ornaments. The defines of the major, I think is the use of many different materials to create the artwork and try to use the craft to make the art out of the paper.
I have been talking to Yi Zhang, she never learned this program before. I introduced her a little bit about the jewellery design and showed her some of my work. She says that it was amazing and asks me if it was too difficult and expensive to make. I told her I think it was easier than painting, just my opinion. For the financial, some people always thought that jewellery is an expensive major, but in fact, sometimes we just use the cheap metal like copper or silver. I never used gold before. I also try to use other materials like glasses to make rings, the effects is still very good.`
}

export let blurb = `This book was typeset in +:marker [NAME TBD] +:/reset Tool. +:marker [NAME TBD] +:/reset is a result of an interrogation of typographic vocabulary; vocabulary implemented as code. +:marker [NAME TBD] +:/reset uses this implementation of typographic vocabulary that affords the user functions such as: 

1. basic typesetting
2. page composition
3. ability to play with various impositions 
4. explore alternative forms of books

Release for +:marker [NAME TBD] +:/reset is pending. +:marker [NAME TBD] +:/reset can be accessed and used through assembling parts from +:marker [github.com/caizoryan] +:/reset repositories or through friendship with developer.`


export let names = `Jinhao Liang
Grace Park
Yi Zhang
Chenen Joan Zhu`
export let credits = `2 or 3 Things I Know About OCAD
 
${names}
 
EAD Expanded, Fall 2025
 
Instructors
Sanam Bahavar
Craig Rodmore
 
Program Coordinator, English for Art and Design and Special Projects
Elaine Munro
 
Manager, Business Strategy
Javier Machado
 
Design
Aaryan Pashine & Craig Rodmore`
